### PR TITLE
Add media queries to make the headers on the landing page responsive

### LINKED ISSUE #13: [BUG REPORT] Make headers responsive on the landing page
The headers don't scale.  We can fix this just by using Bootstrap's display heading feature.

### PR DESCRIPTION
**Pull request by JLeone123**

### CODE REVIEW

**Review by JLeone123 — COMMENTED** [review]
I added just one media query, not multiple.  I shouldn't have said multiple!

**Review by AVS1508 — COMMENTED** [review]
The media query internals look good, but why is the max-height `1000px`? As in, if we have a 1440-by-900 display, and we do a horizontal scale of 1/3 i.e. a 480-by-900 display, the media query will trigger in both scenarios, which might not be good for the larger display. What do you think?

**Comment by JLeone123** [comment]
Hey Aditya, that is a valid point.  I made it so the font size will change if both conditions are met.  We can discuss it at the meeting.

James

**Review by AVS1508 — APPROVED** [review]
Alright, looks good!

**Pull request merged**
